FROM harbor.eli-beams.eu/proxy-dockerhub/node:22-alpine

# Create group and user with GID/UID 1200
RUN groupadd -g 1200 appgroup && \
    useradd -u 1200 -g 1200 -m -s /bin/bash appuser

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

COPY . .

ENV HOSTNAME=0.0.0.0

EXPOSE 8082

# Copy files and set ownership during copy
RUN chown 1200:1200 /app/

# Run container as UID 1200, GID 1200
USER 1200:1200

CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0"]