import type { Metadata } from 'next'
import './globals.css'
import NavigationBar from '@/components/navigation/navigation-bar'
import { StatusBar } from './components/status-bar'
import { Providers } from './providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <NavigationBar />
          <main className="layout-container">
            <StatusBar />
            <div className="page-container">{children}</div>
          </main>
        </Providers>
      </body>
    </html>
  )
}
