services:
  mock-backend:
    build:
      context: ./backend/mockup-websocket-server
      dockerfile: Dockerfile.quickstart
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.quickstart
    depends_on:
      - mock-backend
    environment:
      NEXTAUTH_SECRET: local-dev-secret
      NEXTAUTH_URL: http://localhost:8082/api/auth
      API_URL: localhost:8080
      ZONE_CODE: test
      CONFIG_DIR: /app/zone-config
      NODE_ENV: development
    volumes:
      - ./eli-hmi-config:/app/zone-config:ro
    ports:
      - "8082:8082"
