/**
 * Single write entry point: every action in the UI is a PV write.
 *
 * `pvName` is the canonical PV identifier (e.g. `BI_NL2_SHUTTER`,
 * `AI_NL2_ATT`, `CMD_NL2_START_LASER`). Command PVs (prefix `CMD_`) trigger
 * coordinated effect chains on the backend; plain PVs are direct writes.
 */

import { getSession } from 'next-auth/react'

// Resolved lazily so vitest's beforeEach `stubEnv` takes effect (constants.ts
// captures the env at module-import time, before stubs run).
//
// `NEXT_PUBLIC_API_URL` is `host:port` (e.g. `localhost:8080`); the scheme
// comes from `NEXT_PUBLIC_API_SCHEME` (default `http`). For TLS deployments
// set `NEXT_PUBLIC_API_SCHEME=https`.
//
// Falls back to `localhost:8080` if the env var is unset in non-production —
// without this an unset NEXT_PUBLIC_API_URL produces opaque "http://undefined/..."
// fetch errors at write-time instead of at boot.
//
// PV name handling: this module passes `pvName` to the backend verbatim.
// L4 OPCPA names are already fully-qualified wire names (`BI_<L>_SHUTTER`,
// `AI_TEMP_<L>_REGEN`, `CMD_<L>_<NAME>`, …) generated by
// `frontend/src/app/(modules)/l4-opcpa/lib/pv-names.ts`. Reads use the same
// names — section components pass `raw: true` to `useWebSocketData` so the
// dev-prefix mapping is skipped on both sides. Read/write symmetry is
// preserved.
//
// Reconciliation with `getPrefixedPV` is tracked in #32 (will become
// relevant once the python backend lands and the L4 PV catalog moves
// behind the same prefix scheme as the vacuum modules).
function apiBase(): string {
  const env = process.env.NEXT_PUBLIC_API_URL
  const scheme = process.env.NEXT_PUBLIC_API_SCHEME || 'http'
  if (!env || env === 'undefined') {
    if (process.env.NODE_ENV !== 'production') {
      return `${scheme}://localhost:8080`
    }
    throw new Error(
      'NEXT_PUBLIC_API_URL is not set; cannot determine backend URL',
    )
  }
  return `${scheme}://${env}`
}

interface WriteResult {
  ok: boolean
  error?: string
}

let warnedAuthFallback = false

async function authHeaders(): Promise<Record<string, string>> {
  // Bound getSession with a short timeout — in some dev configurations
  // /api/auth/session can hang and would otherwise block every write.
  // Clear the timeout when getSession wins so we don't leak a 1.5s pending
  // timer on every call.
  let timer: ReturnType<typeof setTimeout> | undefined
  const session = await Promise.race([
    getSession().finally(() => {
      if (timer !== undefined) clearTimeout(timer)
    }),
    new Promise<null>((resolve) => {
      timer = setTimeout(() => resolve(null), 1500)
    }),
  ])
  if (!session?.accessToken && !warnedAuthFallback) {
    warnedAuthFallback = true
    console.warn(
      '[pvWrite] No session token resolved within 1.5s; falling back to ' +
        'placeholder Authorization header. Backend mock accepts this; ' +
        'real backend will reject — check /api/auth/session.',
    )
  }
  const token = session?.accessToken ?? 'dev-no-session'
  return { Authorization: `Bearer ${token}` }
}

export async function pvWrite(
  pvName: string,
  value: number | string,
): Promise<void> {
  const auth = await authHeaders()
  const res = await fetch(`${apiBase()}/pv/${encodeURIComponent(pvName)}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...auth },
    body: JSON.stringify({ value }),
  })
  if (!res.ok) {
    // Try to surface the server's diagnostic body — operators debugging a
    // failed sequence shouldn't have to look at the Network tab for the
    // actual reason.
    const detail = await readErrorDetail(res)
    throw new Error(
      `PV write ${pvName} failed (HTTP ${res.status})${detail ? `: ${detail}` : ''}`,
    )
  }
  const data = (await res.json().catch(() => ({}))) as WriteResult
  if (data && data.ok === false) {
    throw new Error(data.error || `PV write ${pvName} failed`)
  }
}

async function readErrorDetail(res: Response): Promise<string | null> {
  try {
    const text = await res.text()
    if (!text) return null
    try {
      const parsed = JSON.parse(text) as { error?: string }
      return parsed?.error ?? text.slice(0, 200)
    } catch {
      return text.slice(0, 200)
    }
  } catch {
    return null
  }
}

export async function listWaveforms(): Promise<string[]> {
  const auth = await authHeaders()
  const res = await fetch(`${apiBase()}/waveforms`, { headers: auth })
  if (!res.ok) throw new Error(`waveforms list HTTP ${res.status}`)
  const data = await res.json()
  return Array.isArray(data) ? data : []
}
