schemaVersion: 1
heading: P3
interlocks:
  title: P3 Interlocks
  checkClearPv: E3-P3-P3_CHAMBER:INTERLOCK
  items:
    - pvname: E3-P3-P3_CHAMBER:INTERLOCK
      title: P3 Chamber
    - pvname: E3-P3-CRYO1:INTERLOCK
      title: P3 Cryopump CRYO1
    - pvname: E3-P3-CRYO2:INTERLOCK
      title: P3 Cryopump CRYO2
    # TODO: PV name unclear.
    - pvname: L3BT-VCS-EGV501:INTERLOCK
      title: Valve EGV501
    # TODO: PV name unclear; legacy config reused EGV501 here.
    - pvname: L3BT-VCS-EGV501:INTERLOCK
      title: Valve SGV503
safetyPermission:
  title: P3 Machine Safety Permissions
  items:
    # TODO: PV name unclear.
    - pvname: L3BT_ROUGNING:INTERLOCK
      title: P3 Chamber Roughing
    # TODO: PV name unclear.
    - pvname: L3BT_HIGH_VACUUM:INTERLOCK
      title: P3 Chamber High Vacuum Pumping
    # TODO: PV name unclear.
    - pvname: E3-P3-CRYO1_Cooling:INTERLOCK
      title: P3 Cryopump CRYO1 Cooling
    # TODO: PV name unclear.
    - pvname: E3-P3-CRYO2_Cooling:INTERLOCK
      title: P3 Cryopump CRYO2 Cooling
    # TODO: PV name unclear.
    - pvname: L3BT-VCS-EGV501_TOOPEN:INTERLOCK
      title: Valve EGV501 to Open
    # TODO: PV name unclear; legacy config reused EGV501 here.
    - pvname: L3BT-VCS-EGV501_TOOPEN:INTERLOCK
      title: Valve SGV503 to Open
cleanDryAir:
  title: P3 Clean Dry Air (CDA)
  volumes:
    - title: P3 CDA Valve Actuation
      pressure:
        pvName: E3-P3-PPS801:CDA_PRESSURE
        label: PPS801
        options:
          format: precision
      # TODO: PV name unclear.
      flow:
        pvName: E3-P3-PPS801:FLOW
        label: PPFS801
        options:
          format: precision
backing:
  title: P3 Backing
  sensorBar:
    title: P3 Backing Line
    label: Pressure
    height: 20rem
    sensorPVs:
      - pvName: E3-P3-APG802:PRESSURE
        label: APG802
  pump:
    title: Backing Pump P028
    # TODO: PV name unclear.
    rpmPV: AI_RPM_SPEED_P01
    # TODO: PV name unclear.
    valvePv: BI_PUMP_P01
    valveLabel: P028
roughing:
  title: Roughing
  sensorBar:
    title: Roughing Line, P3 Outlet
    label: Pressure
    height: 20rem
    # TODO: PV name unclear; legacy config labelled the APG802 PV as APG801.
    sensorPVs:
      - pvName: E3-P3-APG802:PRESSURE
        label: APG801
  pump:
    title: Roughing Pump P000
    # TODO: PVs unknown.
    rpmPV: AI_RPM_SPEED_P000
    # TODO: PVs unknown.
    valvePv: BI_PUMP_GV000
    valveLabel: GV000
  locking:
    label: Used and Locked By
    # TODO: PV name unclear.
    pvName: SI_LOCKED
